stage:
  host: chorus-staging
  install_path: ~/chorusrails-deploy-new
  postgres_build: 2

upgrade21:
  host: chorus-chorus21-upgrade
  legacy_path: ~/chorus
  postgres_build: 2
  install_path: ~/chorusrails

fresh_install:
  host: chorus-freshinstall
  postgres_build: 2
  install_path: ~/chorusrails_freshinstall
  clean_install: true